from app.ext import db

import datetime

class GlobalFiler(db.Document):
	SampleID = db.StringField(max_length=30,required=True)
	D3S1358 = db.StringField(max_length=20)
	vWA = db.StringField(max_length=20)
	D16S539 = db.StringField(max_length=20)
	CSF1PO = db.StringField(max_length=20)
	TPOX = db.StringField(max_length=20)
	Yindel = db.StringField(max_length=20)
	Amel = db.StringField(max_length=20)
	D8S1179 = db.StringField(max_length=20)
	D21S11 = db.StringField(max_length=20)
	D18S51 = db.StringField(max_length=20)
	DYS391 = db.StringField(max_length=20)
	D2S441 = db.StringField(max_length=20)
	D19S433 = db.StringField(max_length=20)
	TH01 = db.StringField(max_length=20)
	FGA = db.StringField(max_length=20)
	D22S1045 = db.StringField(max_length=20)
	D5S818 = db.StringField(max_length=20)
	D13S317 = db.StringField(max_length=20)
	D7S820 = db.StringField(max_length=20)
	SE33 = db.StringField(max_length=20)
	D10S1248 = db.StringField(max_length=20)
	D1S1656 = db.StringField(max_length=20)
	D12S391 = db.StringField(max_length=20)
	D2S1338 = db.StringField(max_length=20)
	add_time = db.DateTimeField(default=datetime.datetime.now)
	
	# title = db.StringField(max_length=200, required=True)
	# keyword = db.StringField(max_length=200, required=True)
	# publicState = db.StringField(max_length=200, required=True)
	# depositoryBank = db.StringField(max_length=200, required=True)
	# businessType = db.StringField(max_length=200, required=True)
	# businessScene = db.StringField(max_length=200, required=True)
	# creator = db.StringField(max_length=200, required=True)
	# content = db.StringField(max_length=200, required=True)
	# createTime = db.DateTimeField(default=datetime.datetime.now)
	# updateTime = db.DateTimeField(default=datetime.datetime.now)
	# viewCount = db.IntField(default=0, required=True)